### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by kgn3400** [cgarwood/homeassistant-fullykiosk#103]
After installing newest version 1.0.2 below errors are logged :

Logger: homeassistant.components.sensor
Source: custom_components/fullykiosk/sensor.py:115 
Integration: Sensor (documentation, issues) 
First occurred: 18.47.23 (6 occurrences) 
Last logged: 18.47.23

Error adding entities for domain sensor with platform fullykiosk
Error while setting up fullykiosk platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/fullykiosk/sensor.py", line 115, in state
    time = parser.parse(self.coordinator.data[self._sensor])
  File "/usr/local/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 14.05.2022 14.22.43

And:

Logger: homeassistant
Source: custom_components/fullykiosk/sensor.py:115 
Integration: Fully Kiosk Browser (documentation, issues) 
First occurred: 18.47.50 (24 occurrences) 
Last logged: 18.49.50

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 270, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/fullykiosk/sensor.py", line 115, in state
    time = parser.parse(self.coordinator.data[self._sensor])
  File "/usr/local/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dateutil/parser/_parser.py", line 643, in parse
    raise ParserError("Unknown string format: %s", timestr)
dateutil.parser._parser.ParserError: Unknown string format: 13.05.2022 19.16.20

Rolling back to version 1.0.1 fixes above errors.

Best regards
Kurt Nielsen

**Comment by cgarwood** [comment]
Seems like Fully returns the last app start date in different formats, probably based on locale, and Python's dateutil can't parse all of them. May be time to remove that sensor

**Comment by spider7611** [comment]
Have the same problem. Going back to version 1.01.
