### ISSUE TITLE
Unexpected error on adding integration

### ISSUE THREAD

**Issue by bravosp** [cgarwood/homeassistant-fullykiosk#112]
Hi,

On attempting adding the integration and entering my IP and remote password, I get an 'Unexpected Error' thrown up which prevents me from adding the integration. Have tried a couple of time now. I'm running Home Assistant OS core-2022.7.0b2 and tried to install the latest version of homeassistant-fullykiosk. Below is the log and would appreciate any support you can give.

Thanks,

Johnny

`This error originated from a custom integration.

Logger: custom_components.fullykiosk.config_flow
Source: custom_components/fullykiosk/config_flow.py:49 
Integration: Fully Kiosk Browser (documentation, issues) 
First occurred: 18:07:13 (3 occurrences) 
Last logged: 18:28:53

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/fullykiosk/config_flow.py", line 50, in validate_input
    deviceInfo = await fully.getDeviceInfo()
  File "/usr/local/lib/python3.10/site-packages/fullykiosk/__init__.py", line 30, in getDeviceInfo
    result = await self.sendCommand("deviceInfo")
  File "/usr/local/lib/python3.10/site-packages/fullykiosk/__init__.py", line 22, in sendCommand
    data = await self._rh.get(
  File "/usr/local/lib/python3.10/site-packages/fullykiosk/__init__.py", line 139, in get
    async with self.session.get(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/fullykiosk/config_flow.py", line 80, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/fullykiosk/config_flow.py", line 49, in validate_input
    with timeout(15):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 116, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
`

**Comment by onedr0p** [comment]
I upgraded to 2022.7.0 and maybe got something related?

```
Logger: homeassistant.setup
Source: setup.py:162
First occurred: 7:45:03 PM (1 occurrences)
Last logged: 7:45:03 PM

Setup failed for custom integration fullykiosk: Unable to import component: No module named 'fullykiosk'
```

**Comment by frantathefranta** [comment]
HASS 2022.7 has updated python to 3.10, that's probably wreaking havoc here as well.

**Comment by bcutter** [comment]
> HASS 2022.7 has updated python to 3.10, that's probably wreaking havoc here as well.

Interesting, as I'm currently reading the [2022.7 release notes](https://www.home-assistant.io/blog/2022/07/06/release-20227/#breaking-changes) and was wondering if fullykiosk is **"Python 3.10 ready"**.

Can you answer that question please @cgarwood ?

**Comment by cgarwood** [comment]
@bcutter working fine on Python 3.10 for me (HA OS on my main system)

OP is getting a TimeoutError, so it appears the tablet isn't responding to HA's requests fast enough. I've seen that happen with lower spec hardware, and at one point on Kindle's especially the remote admin API would just stop responding all together for a while and come back.

@onedr0p you're missing the python library that the component uses. Home Assistant should install it automatically though. How are you running HA? (venv/container/OS/etc)

**Comment by onedr0p** [comment]
The issue was fixed on home assistant 2022.7.4.

**Comment by frantathefranta** [comment]
Yeah I'm trying this with a 2019 Kindle Fire and getting the same error. Any advice on how to make the API respond quicker so it registers?
