### ISSUE TITLE
Error while setting up fullykiosk platform for light

### ISSUE THREAD

**Issue by vlad36N** [cgarwood/homeassistant-fullykiosk#41]
Have latest Fully Kiosk Browser integration for Home Assistant 0.1.3 using HACS.
Home Assistant 2021.3.2
Host Operating System | Home Assistant OS 5.12
Supervisor Version | supervisor-2021.03.4
Docker Version | 19.03.13

Error:

Logger: homeassistant.components.light
Source: custom_components/fullykiosk/light.py:42
Integration: Light (documentation, issues)
First occurred: 9:44:19 AM (2 occurrences)
Last logged: 9:44:19 AM

    Error adding entities for domain light with platform fullykiosk
    Error while setting up fullykiosk platform for light

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 319, in _async_write_ha_state
    sstate = self.state
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 693, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/fullykiosk/light.py", line 42, in is_on
    return self.coordinator.data["screenOn"]
KeyError: 'screenOn'

**Comment by cgarwood** [comment]
What version of Fully Kiosk Browser are you running on the tablet?

**Comment by vlad36N** [comment]
App version | 1.43.1-fire, PLUS LICENSE
Android version | 9 (SDK 28)

**Comment by bcutter** [comment]
What´s the current status on this @vlad36N ?

**Comment by cgarwood** [comment]
Going to close this since it's a year old. Try updating to a newer Fully Kiosk version if you haven't already (& the latest version of the component).
