### ISSUE TITLE
Longer timeout for older/slower devices

### ISSUE THREAD

**Issue by BigWebstas** [cgarwood/homeassistant-fullykiosk#42]
i keep hitting this error im thinking its because my  devices are on 2.4 and they are kindle 5th gen tablets and it takes 5-30 seconds for the admin page to load in a browser

> Logger: custom_components.fullykiosk.config_flow
Source: custom_components/fullykiosk/config_flow.py:50
Integration: fullykiosk (documentation, issues)
First occurred: 8:15:20 AM (1 occurrences)
Last logged: 8:15:20 AM

>Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/fullykiosk/config_flow.py", line 50, in validate_input
    deviceInfo = await fully.getDeviceInfo()
  File "/usr/local/lib/python3.8/site-packages/fullykiosk/__init__.py", line 29, in getDeviceInfo
    result = await self.sendCommand("deviceInfo")
  File "/usr/local/lib/python3.8/site-packages/fullykiosk/__init__.py", line 21, in sendCommand
    data = await self._rh.get(
  File "/usr/local/lib/python3.8/site-packages/fullykiosk/__init__.py", line 120, in get
    async with self.session.get(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
asyncio.exceptions.CancelledError

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/config/custom_components/fullykiosk/config_flow.py", line 80, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/fullykiosk/config_flow.py", line 50, in validate_input
    deviceInfo = await fully.getDeviceInfo()
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 45, in __exit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py", line 92, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

**Comment by BigWebstas** [comment]
![fully](https://user-images.githubusercontent.com/2896329/112488277-01f39d00-8d43-11eb-83d1-59c4ede4c1ef.gif)

**Comment by cgarwood** [comment]
I bumped the timeout from 10 seconds to 15 seconds, hopefully that will help. https://github.com/cgarwood/homeassistant-fullykiosk/pull/45
